name: CI-ubuntu-latest

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up CMake
      uses: cmake/setup-cmake@v1
      with:
        cmake-version: '3.21'
      
    - name: Build and test
      run: |
        cmake --build . --target uCTestDemo
        cd build
        ./uCTestDemo
