name: CI-ubuntu-latest

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up CMake
      uses: martinlindhe/cmake-action@v2
      with:
        cmakeListsTxtPath: CMakeLists.txt
        buildDir: build
      
    - name: Build and test
      run: |
        cmake --build build --target uCTestDemo
        cd build
        ./uCTestDemo
